package com.example.util;

import java.math.BigDecimal;

public class TestConstants {
    public static final String URL_BOOK = "/books";
    public static final String URL_BOOK_ID = "/books/{id}";
    public static final String URL_BOOK_SEARCH = "/books/search";
    public static final String URL_CATEGORY = "/categories";
    public static final String URL_CATEGORY_ID = "/categories/{id}";
    public static final String URL_CATEGORY_ID_BOOKS = "/categories/{Id}/books";
    public static final String EMPTY_STRING = "";
    public static final String EXCLUDE_ID = "id";
    public static final String PAGE = "page";
    public static final String SIZE = "size";
    public static final String GET_CONTENT = "content";
    public static final String CONTENT = "$.content";
    public static final String CONTENT_LENGTH = "$.content.length()";
    public static final int ZERO = 0;
    public static final Long ONE = 1L;
    public static final Long TWO = 2L;
    public static final Long THREE = 3L;
    public static final Long TEN = 10L;
    public static final Long NON_EXISTING_ID = 999L;
    public static final String CATEGORY_NAME = "Test name1";
    public static final String CATEGORY_DESCRIPTION = "Description test1";
    public static final String BOOK_TITLE = "Title";
    public static final String BOOK_AUTHOR = "Author";
    public static final String BOOK_ISBN = "ISBN123456789";
    public static final BigDecimal BOOK_PRICE = BigDecimal.valueOf(99.0);
    public static final String BOOK_DESCRIPTION = "Description test";
    public static final String BOOK_COVER_IMAGE = "https://example.com/tast-cover-image.jpg";
    public static final String BOOK_TITLE_1 = "Title test1";
    public static final String BOOK_AUTHOR_1 = "Author test1";
    public static final String BOOK_ISBN_1 = "ISBN1234567891";
    public static final BigDecimal BOOK_PRICE_1 = BigDecimal.valueOf(9.99);
    public static final String BOOK_DESCRIPTION_1 = "Description test1";
    public static final String BOOK_COVER_IMAGE_1 = "https://example.com/tast-cover-image-1.jpg";
    public static final String BOOK_TITLE_2 = "Title test2";
    public static final String BOOK_AUTHOR_2 = "Author test2";
    public static final String BOOK_ISBN_2 = "ISBN1234567892";
    public static final BigDecimal BOOK_PRICE_2 = BigDecimal.valueOf(99.99);
    public static final String BOOK_DESCRIPTION_2 = "Description test2";
    public static final String BOOK_COVER_IMAGE_2 = "https://example.com/tast-cover-image-2.jpg";
    public static final String BOOK_TITLE_3 = "Title test3";
    public static final String BOOK_AUTHOR_3 = "Author test3";
    public static final String BOOK_ISBN_3 = "ISBN1234567893";
    public static final BigDecimal BOOK_PRICE_3 = BigDecimal.valueOf(999.99);
    public static final String BOOK_DESCRIPTION_3 = "Description test3";
    public static final String BOOK_COVER_IMAGE_3 = "https://example.com/tast-cover-image.jpg-3";
    public static final String UPDATE_BOOK_TITLE = "Update Title";
    public static final String UPDATE_BOOK_AUTHOR = "Update Author";
    public static final String UPDATE_BOOK_ISBN = "ISBN1234567899";
    public static final BigDecimal UPDATE_BOOK_PRICE = BigDecimal.valueOf(99.9);
    public static final String UPDATE_BOOK_DESCRIPTION = "Update Description test";
    public static final String UPDATE_BOOK_COVER_IMAGE = "https://example.com/tast-cover-image-update.jpg";
    public static final String CATEGORY_NAME_1 = "Test name1";
    public static final String CATEGORY_DESCRIPTION_1 = "Description test1";
    public static final String CATEGORY_NAME_2 = "Test name2";
    public static final String CATEGORY_DESCRIPTION_2 = "Description test2";
    public static final String CATEGORY_NAME_3 = "Test name3";
    public static final String CATEGORY_DESCRIPTION_3 = "Description test3";
    public static final String UPDATE_CATEGORY_NAME = "Update Category name";
    public static final String UPDATE_CATEGORY_DESCRIPTION = "Update Description";
}
